// <auto-generated />
using System;
using BitWise.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BitWise.Migrations.CoursesDb
{
    [DbContext(typeof(CoursesDbContext))]
    partial class CoursesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BitWise.Models.Entities.CourseName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CourseNames");
                });

            modelBuilder.Entity("BitWise.Models.Entities.CourseTopics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CourseNameId")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseNameId");

                    b.ToTable("CourseTopics");
                });

            modelBuilder.Entity("BitWise.Models.Entities.TopicDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseTopicsId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseTopicsId");

                    b.ToTable("TopicDescriptions");
                });

            modelBuilder.Entity("BitWise.Models.Entities.TopicImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseTopicsId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseTopicsId");

                    b.ToTable("TopicImages");
                });

            modelBuilder.Entity("BitWise.Models.Entities.CourseTopics", b =>
                {
                    b.HasOne("BitWise.Models.Entities.CourseName", null)
                        .WithMany("CourseTopics")
                        .HasForeignKey("CourseNameId");
                });

            modelBuilder.Entity("BitWise.Models.Entities.TopicDescription", b =>
                {
                    b.HasOne("BitWise.Models.Entities.CourseTopics", null)
                        .WithMany("TopicDescriptions")
                        .HasForeignKey("CourseTopicsId");
                });

            modelBuilder.Entity("BitWise.Models.Entities.TopicImage", b =>
                {
                    b.HasOne("BitWise.Models.Entities.CourseTopics", null)
                        .WithMany("TopicImages")
                        .HasForeignKey("CourseTopicsId");
                });

            modelBuilder.Entity("BitWise.Models.Entities.CourseName", b =>
                {
                    b.Navigation("CourseTopics");
                });

            modelBuilder.Entity("BitWise.Models.Entities.CourseTopics", b =>
                {
                    b.Navigation("TopicDescriptions");

                    b.Navigation("TopicImages");
                });
#pragma warning restore 612, 618
        }
    }
}
